### PR TITLE
updated readme for master branch

### PR DESCRIPTION
**Pull request by Alaev**
Suggesting to add the following info the readme file.

### CODE REVIEW

**Comment by eXtremeXR** [comment]
Absolutely! Thank you for the added description, README is now much better!

**Comment by Alaev** [comment]
Great!!

Next time just for the git way of working.
It would be better if you review it as say its ok via git. then assignees me to the merge. this way we would have control of the work flow.

**Comment by Alaev** [comment]
I will add tests for each part under the branch name with _with_tests prefix. for easier review.
After that, I will push master to Travis with Codecove for tracking. That way it would be easy for us to setup client next that we are sure the server works well.

**Comment by eXtremeXR** [comment]
Oh okay, sorry I only used GitHub for basic things in the past, so I got a thing or two to learn! 

Will do as you suggested in the future!

**Comment by Alaev** [comment]
It's cool. the first time that I used GIT I was like wtf wtf wtf... after some time you git it going :)
I am going to set up Travis now for part 4. not sure if should we use Jest or Mocha, trying to fix the right answer for it.

**Comment by eXtremeXR** [comment]
Awesome! To be honest I didn't touch Travis, just heard about it - I'll read more about it to try to understand what you just said :)

Yeah basic Git is okay, but some of the advanced ways of using it is confusing. I remember freaking out when merge conflicts happened, haha!

**Pull request merged**
