### PR TITLE
Unit test is fun

### PR DESCRIPTION
**Pull request by Alaev**
Added unit test for user controller

### CODE REVIEW

**Comment by Alaev** [comment]
@eXtremeXR added a unit test, folder refactoring for better scale I will try to finish the HTTP route test today, however, I think the controller is the most important as it's the hardest to test.

**Comment by Alaev** [comment]
@eXtremeXR  finished with unit tests. looks like all the functionality works as expected 🎉 
it will be hard to get 100% for all the files as I added some if statements for test env.
if you have any question feel free to ask

**Comment by eXtremeXR** [comment]
Whoa! Looking awesome! Good job :1st_place_medal: 
I'll take my time and go through this and I will create new "issues" if I have any questions. 
Thanks a lot for this!

Feel free to merge it with master! :)

**Review by eXtremeXR — APPROVED** [review]
Looking great!

**Comment by Alaev** [comment]
@eXtremeXR if you want I can make a screen cast showing how I think about the test and my approach for testing after you merge the pull request

**Comment by eXtremeXR** [comment]
Oh of course, I mean whatever you want/prefer, after all this is your piece! :)
You want me to merge it? Before you wanted me to assign you and let you do it, so I'm a bit confused hehe.

Also be sure to accept me on Hangouts, I believe I sent invite, if you don't see me add (codeworkr@gmail.com).

**Comment by Alaev** [comment]
@eXtremeXR I don't see any notification in hangouts... send me an email I will reply back this way it will add you to my list. about the video I don't mind I can make one or if you want you can cover it too. unit testing is very important I think and it is not covered deeply in tutorials...

**Comment by Alaev** [comment]
Merged.

**Comment by eXtremeXR** [comment]
Just sent you an email, let's see if it works!
Yeah, like I said, I wouldn't mind it at all, in fact it's a great idea since you wrote this code and you know testing better than I know it.

**Pull request merged**
